kubernetes/docs/README.md, kubernetes/docs/monitoring.md, kubernetes/template/DeploymentTemplates/MainTemplate.json, kubernetes/template/DeploymentTemplates/azuredeploy.json
First iteration of the monitoring guidelines doc
=> Added monitoring guide under docs directory

servicefabric/Test/azuredeploy.parameters.json
=> Update test parameter

kubernetes/template/DeploymentTemplates/createUiDefinition.json
Updating Allowed Values for the master node to 1
=> Updating the master node allowed values

kubernetes/template/DeploymentTemplates/MainTemplate.json, kubernetes/template/DeploymentTemplates/azuredeploy.json
Update AKSe version default to point to latest version.
This is also needed for windows node support.
=> feat: update AKSe version default to point to latest version

diagnosis/getkuberneteslogs.sh
=> Log Collector Process dvm host

kubernetes/template/DeploymentTemplates/MainTemplate.json, kubernetes/template/DeploymentTemplates/azuredeploy.json, kubernetes/template/DeploymentTemplates/createUiDefinition.json, kubernetes/template/strings/resources.resjson
Update 
K8s version to include 1.13, 1.14 and 1.15.
AKSe version to 0.39.2.
=> feat: update K8s and AKSe version.

kubernetes/template/DeploymentTemplates/azuredeploy.json, kubernetes/template/strings/resources.resjson
=> feat: update git branch value.

kubernetes/template/strings/resources.resjson
docs: description changes for marketplace
=> docs: description changes for marketplace

kubernetes/template/DeploymentTemplates/MainTemplate.json
Fix default value for gallery branch in main template
=> bug: fix default value for gallery branch in main template

diagnosis/getkuberneteslogs.sh
=> Fix --api-model parameter

kubernetes/template/DeploymentTemplates/MainTemplate.json, kubernetes/template/DeploymentTemplates/azuredeploy.json, kubernetes/template/DeploymentTemplates/clusterDefinition.json
feat: move to latest akse version.
=> feat: move to latest akse version.

kubernetes/template/DeploymentTemplates/MainTemplate.json, kubernetes/template/DeploymentTemplates/azuredeploy.json
=> chore: Move up aksengine version.

kubernetes/template/DeploymentTemplates/azuredeploy.parameters.json
=> chore: Update node distro defaults.

kubernetes/template/DeploymentTemplates/clusterDefinition.json
Update the image version details to use AKSEngine defaults
=> fix: Update the image version details to use AKSEngine defaults

AKSEngine-E2E/AksTest-Scripts/aksEngineScale.sh, AKSEngine-E2E/AksTest-Scripts/aksEngineUpgrade.sh, AKSEngine-E2E/Template/script.sh
time sync is a known flake at present w/ 18.04-LTS
=> skip sync time e2e test

registry/Scripts/pre-reqs.ps1
Print sku details in ContainerRegistryPrerequisites function
=> fix: Print sku details in ContainerRegistryPrerequisites function.

registry/diagnosis/collectlogs.sh, registry/diagnosis/getcontainerregistrylogs.sh, registry/diagnosis/getkuberneteslogs.sh
Script to collect docker registry log from the vm
=> feature: Script to collect docker registry log from the vm

diagnosis/collectlogs.sh, registry/diagnosis/collectlogs.sh, registry/diagnosis/getcontainerregistrylogs.sh
Creating a zip file rather coping all individual log files
=> feat: Creating a zip file rather coping all individual log files

registry/Scripts/pre-reqs.ps1, registry/Scripts/self-signed.ps1
Improvements in cert and pre-reqs scripts
=> fix: Improvements in cert and pre-reqs scripts

registry/Scripts/pre-reqs.ps1, registry/diagnosis/collectlogs.sh
DNS zone commandlet and some error case improvements
=> feat: DNS zone commandlet and some error case improvements

registry/DeploymentTemplates/azuredeploy.json, registry/DeploymentTemplates/azuredeploy.parameters-example.json, registry/DeploymentTemplates/createUiDefinition.json, registry/manifest.json
Move to registry version 1.0.3 and update VHD defaults to Oct vhd
=> Move to registry version 1.0.3 and update VHD defaults to Oct vhd

AKSEngine-E2E/AksTest-Scripts/aksEngineScale.sh
This enables to capture the test results both during scale down and scale up e2e operations
=> Fix for scale test results file name

diagnosis/scripts/updateconfiguration.sh, kubernetes/template/DeploymentTemplates/clusterDefinition.json
Update existing cluster with Azure Stack recommended configuration.
@jadarsie : Check-in file in diagnosis folder so that we can use it for TSG as well.
=> Update existing cluster with Azure Stack recommended configuration.

diagnosis/README.md, diagnosis/collectlogs.sh, diagnosis/getkuberneteslogs.sh, diagnosis/hosts.sh, diagnosis/k8sCollectLogsCi.sh, diagnosis/scripts/release.sh
Update: additional cloud provider log based on PR https://github.com/Azure/aks-engine/pull/3792
=> additional files for release zip

registry/Scripts/pre-reqs.ps1
Update prerequisite script to support updated commandlets keyvault access
=> Update prerequisite script to support updated commandlets keyvault access

registry/Scripts/pre-reqs.ps1
Fix powershell parameter for setting key vault access policy for AAD env
=> Fix service principal name for aad env
